### ISSUE TITLE
Commands command fails

### ISSUE THREAD

**Issue by deniscostadsc** [bltavares/kickstart#10]
When you run kickstart with any parameters it suppose to show all available commands, like this:

```
$ kickstart
kickstart
Bash provisioning support

Available commands are:
create
doc
docker-create
bootstrap
deploy
infect
commands
autocomplete
local
help
docker-ssh
init
root-dir
compile

Happy hacking (:
```

But instead I got this:

```
$ kickstart
kickstart
Bash provisioning support

Available commands are:
find: warning: the -d option is deprecated; please use -depth instead, because the latter is a POSIX-compliant feature.
find: paths must precede expression: 1
Try 'find --help' for more information.

Happy hacking (:
```

The error is caused by [this line](https://github.com/bltavares/kickstart/blob/9fd8dcbca095c39de2b8febb97ea82076f4021ec/lib/kickstart-commands#L4). It uses the option "-d" of find. Reading [find's manpage](https://linux.die.net/man/1/find) I realized that, on Linux, that option only changes how find traverses the file system. Based on the "1" aside "-d", I think the intention was to limit the maximum depth. On Linux that is done with the option "-maxdepth". But  there is no nested folder so far, so I assume that this line solve the problem I reported:

```
find "$root_dir"/lib | cut -f2- -d'-'
```

But that also show the path used in find:

```
$ kickstart
kickstart
Bash provisioning support

Available commands are:
/path/used/in/find/kickstart/lib
create
doc
docker-create
bootstrap
deploy
infect
commands
autocomplete
local
help
docker-ssh
init
root-dir
compile

Happy hacking (:
```

So, finally, I'd suggest though this:

```
find "$root_dir"/lib | grep "kickstart-" | cut -f2- -d'-'
```

I can do the PR, if it's OK for you.

PS: Only tested on Ubuntu.

:heart:

**Comment by bltavares** [comment]
Thanks for reporting with such a great description @deniscostadsc

I'm pulling your changeset, and doing a minor change to use `find` itself to select the commands.
