### ISSUE TITLE
kickstart.package.manager behaves differently under DEBUG

### ISSUE THREAD

**Issue by deniscostadsc** [bltavares/kickstart#11]
When running a deploy using the DEBUG flag, some package manager steps failed. That happens because the command kickstart.package.manager under debug returns `/usr/bin/apt-get apt-get` instead of `apt-get`.

This is caused by `kickstart.mute`, that under DEBUG, stop supressing the output of commands and causes `kickstart.command_exists` to echo the actual path of `apt-get`.

I'd recommend that `kickstart.command_exists` to be changed to this:

```
kickstart.command_exists() {
  which "$1" > /dev/null
}
```

This works and still showing the execution when debugging, as you can see here:

```
...
++ kickstart.package.manager
++ kickstart.command_exists apt-get
++ which apt-get
++ echo apt-get
++ return 0
+ echo apt-get
apt-get
+ echo Done
Done
```

To reproduce you can create a new project following these steps:

```
$ kickstart create
$  echo 'echo $(kickstart.package.manager)' > install.sh
$ DEBUG=1 kickstart local
```

I can PR this change if it's OK for you.

PS: only tested on Ubuntu

:heart:

**Comment by bltavares** [comment]
Thanks for the great issue description again @deniscostadsc. I'm merging this after testing on Mac as well.
